### PR TITLE
mvt: enable test after publishing

### PR DESCRIPTION
**Pull request by ibgreen**
Restore tests after publishing #626

### CODE REVIEW

**Comment by ibgreen** [comment]
@jesusbotella

**Comment by ibgreen** [comment]
@xintongxia @jesusbotella Looks like now that the module is published, the tests will pass on CI. We need a better error message when this happens.

**Comment by jesusbotella** [comment]
Thank you! I tried to see what happened in CI but seems like the exception that puppeteer throws is not developer friendly.
I didn't realized that it couldn't find the files in CI and it was passing in my local environment because lerna links all packages :(

**Comment by ibgreen** [comment]
Yes, also the workers are loaded dynamically from CDN which, while a great feature for bundle size etc, creates some chicken-and-egg dependencies. This was a quite recent addition that took a big push. We definitely need to make another pass to improve the error handling and test cases around this.

**Pull request merged**
