### PR TITLE
glTF: Create TypedArray for the accessor

### PR DESCRIPTION
**Pull request by RAX7**

### CODE REVIEW

**Comment by antoxa2013** [comment]
@ibgreen but if TypedArray created from ArrayBuffer a new typed array view is created that views the specified ArrayBuffer. The memory sharing will not lost. If so then no reason to add more options for postprocessor.

**Comment by ibgreen** [comment]
> The memory sharing will not lost. 

Indeed, the memory sharing is not lost on the CPU, but it is lost on the GPU. 

Most applications will presumably proceed to create WebGL buffers using these accessors, one buffer per accessor, instead of one WebGL buffer per bufferView.

**Comment by ibgreen** [comment]
The typed arrays should really be temporary. In most applications they should be discarded/garbage collected away as soon as the memory has been copied to the GPU.

Of course this is a generic loader and there may be use cases which are not GPU based, but given the nature of the glTF standard and the loaders.gl repo, the WebGL use case should at least be a primary supported use case.

**Comment by ibgreen** [comment]
I guess another option is that we always add these typed arrays but then have the documentation explain that they can be ignored and overwritten with a WebGL bufferView buffer reference if the user wants to share buffers.

**Comment by antoxa2013** [comment]
@ibgreen 
> the memory sharing is not lost on the CPU, but it is lost on the GPU
I did not think about this case. You are right.
I played around with some glTF models and used draco compression. Parser returns me nice and useful TypedArray arrays. Then I switched to uncompressed glTF and TypedArray are disappeared. It looked weird for me and I decide make API more consistent. Now I understand why this was done so.
I will add an option "resolveAccessorValues" later.

**Comment by ibgreen** [comment]
> Then I switched to uncompressed glTF and TypedArray are disappeared.

Yes this is an issue. The idea was that the `GLTFLoader` should remove the draco extension and make it looks as if "it was never there". So that apps would get Draco support for "free". 

But due to this behavior, the application sees a difference.

Let me consider this a bit further tonight when I have more time, I may accept your PR as is.

**Comment by antoxa2013** [comment]
@ibgreen I redid the previous one commit. Added an option _resolveValue_ and test case. But I'm not sure if the test case is done correctly.

**Pull request closed without merging**
