### PR TITLE
Fix Draco loader attribute types

### PR DESCRIPTION
**Pull request by ibgreen**
- No longer generate glTF accessors in the DracoLoader, just standard mesh accessors.
- Adapt DracoLoader output to glTF in GLTFLoader.

### CODE REVIEW

**Comment by ibgreen** [comment]
> Have you tested this with luma?

No, we need a good way to do that. I am porting the gltf example to loaders.gl.

**Comment by georgios-uber** [comment]
We need start-local-loaders for luma

**Comment by georgios-uber** [comment]
Don’t port the same example many times

**Comment by ibgreen** [comment]
> Don’t port the same example many times

My vision for the loaders.gl is that the website has examples for each loader category that allow users to drag-and-drop files to test the loaders directly. The current GLTF loader example fits the bill perfectly!

If the concern is duplicating the GLTF example code in two places, I would argue eventually replacing with a more focused example in luma.gl (maybe showing lights or some other scenegraph feature).

**Pull request merged**
